language: c++
compiler: gcc
group: edge
env:
    global:
        - GCC_VERSION="4.9"
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
    - cmake --version

install:
    - git clone --recursive https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
    - sudo apt-get install fglrx opencl-headers xorg-dev libglu1-mesa-dev
    - gcc --version
script:
    - cmake . -DCMAKE_CXX_COMPILER=$(which $CXX)
    - make
