language: cpp

compiler: gcc

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3.tar.gz
    - tar -xvzf cmake-3.2.3.tar.gz
    - sudo cp -rf cmake-3.2.3/* /usr
    - rm -rf cmake-3.2.3
    - rm cmake-3.2.3.tar.gz

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make